### ISSUE TITLE
Show how to install additional Android dependencies

### ISSUE THREAD

**Issue by vgaidarji** [vgaidarji/android-github-actions#12]
Base build & emulator images have a limited number of Android dependencies installed. It would be nice to show the example of how to install additional Android dependencies since different projects require different versions of SDK.

A test project to use https://github.com/vgaidarji/ci-matters/actions.

**Comment by BeksOmega** [comment]
Hello! Would you be able to help me with this?

I would like to be able to build with Android SDK version 29. But I can't figure out how to properly accept the licenses, get the build tools, etc.

I have tried downloading and accepting the licenses before running your build script, but it still doesn't seem to be working. You can view all of my thrashing [here](https://github.com/BeksOmega/looping-layout/pull/12) hehe.

This is my first time trying to set up CI for a project, so I'd really appreciate any advice you could give me!

Thank you for the wonderful tool, and thank you for your time.
--Beka

**Comment by vgaidarji** [comment]
Hey @BeksOmega. In your https://github.com/BeksOmega/looping-layout/pull/12, you're accepting licenses and installing dependencies not on the same machine. 
Following runs in Docker container which is separate environment from your `Get Build Tools`
```
      - name: Build with Gradle
        uses: vgaidarji/android-github-actions/build@v1.0.0
        with:
          args: './gradlew build'
```

Recently I've migrated actions from this repo to separate repositories as GitHub doesn't support multiple actions being hosted in repository anymore.

See
- https://github.com/vgaidarji/android-github-actions-build
- https://github.com/vgaidarji/android-github-actions-emulator

And here you can find the usage https://github.com/vgaidarji/ci-matters/pull/37.
That PR is still work in progress (open issue with emulator action), but build action is working.
Try this for your PR
```
      uses: vgaidarji/android-github-actions-build@v1.0.1
      with:
        args: "sdkmanager 'platforms;android-29' 'build-tools;29.0.2' && ./gradlew build"
```

**Comment by BeksOmega** [comment]
Thank you so much for the help! Using your new action got it working :D I'm so happy! I really appreciate you taking the time to help me. You're the bomb :bomb:

**Comment by vgaidarji** [comment]
@BeksOmega you're welcome. was happy to help 🙂
